x-logging: &x-logging
  logging:
    driver: json-file
    options:
      max-file: "5"
      max-size: "10m"

services:
  traefik:
    image: traefik:2.11
    <<: *x-logging
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`,`appwrite`)
      - --entrypoints.appwrite_web.address=:80
    restart: unless-stopped
    ports:
      - "20080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - appwrite

  appwrite:
    image: appwrite/appwrite:1.9.0
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=appwrite
      - traefik.docker.network=testing_appwrite
      - traefik.http.services.appwrite_api.loadbalancer.server.port=80
      # Main API
      - traefik.http.routers.appwrite_api.entrypoints=appwrite_web
      - traefik.http.routers.appwrite_api.rule=PathPrefix(`/`)
      - traefik.http.routers.appwrite_api.service=appwrite_api
    volumes:
      - appwrite-uploads:/storage/uploads
      - appwrite-cache:/storage/cache
      - appwrite-config:/storage/config
      - appwrite-certificates:/storage/certificates
      - appwrite-functions:/storage/functions
      - appwrite-builds:/storage/builds
      - appwrite-sites:/storage/sites
    depends_on:
      - mariadb
      - redis
    environment:
      - _APP_ENV=development
      - _APP_LOCALE=en
      - _APP_OPTIONS_ABUSE=disabled
      - _APP_OPTIONS_FORCE_HTTPS=disabled
      - _APP_OPENSSL_KEY_V1=test-secret-key-you-can-change
      - _APP_DOMAIN=localhost
      - _APP_DOMAIN_TARGET=localhost
      - _APP_DOMAIN_FUNCTIONS=functions.localhost
      - _APP_DOMAIN_SITES=sites.localhost
      - _APP_CONSOLE_WHITELIST_ROOT=disabled
      - _APP_CONSOLE_WHITELIST_EMAILS=
      - _APP_CONSOLE_WHITELIST_IPS=
      - _APP_REDIS_HOST=redis
      - _APP_REDIS_PORT=6379
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=user
      - _APP_DB_PASS=password
      - _APP_DB_ROOT_PASS=rootsecretpassword
      - _APP_STORAGE_DEVICE=Local
      - _APP_STORAGE_LIMIT=30000000
      - _APP_FUNCTIONS_SIZE_LIMIT=30000000
      - _APP_FUNCTIONS_TIMEOUT=900
      - _APP_FUNCTIONS_CONTAINERS=10
      - _APP_FUNCTIONS_CPUS=0
      - _APP_FUNCTIONS_MEMORY=0
      - _APP_FUNCTIONS_RUNTIMES=node-22
      - _APP_EXECUTOR_SECRET=executor-secret-key
      - _APP_EXECUTOR_HOST=http://openruntimes-executor/v1
      - _APP_LOGGING_PROVIDER=
      - _APP_LOGGING_CONFIG=
      - _APP_MAINTENANCE_INTERVAL=86400
      - _APP_GRAPHQL_MAX_BATCH_SIZE=10
      - _APP_GRAPHQL_MAX_COMPLEXITY=250
      - _APP_GRAPHQL_MAX_DEPTH=3

  appwrite-realtime:
    image: appwrite/appwrite:1.9.0
    entrypoint: realtime
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - mariadb
      - redis
    environment:
      - _APP_ENV=development
      - _APP_OPENSSL_KEY_V1=test-secret-key-you-can-change
      - _APP_REDIS_HOST=redis
      - _APP_REDIS_PORT=6379
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=user
      - _APP_DB_PASS=password

  appwrite-worker-databases:
    image: appwrite/appwrite:1.9.0
    entrypoint: worker-databases
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - mariadb
      - redis
    environment:
      - _APP_ENV=development
      - _APP_OPENSSL_KEY_V1=test-secret-key-you-can-change
      - _APP_REDIS_HOST=redis
      - _APP_REDIS_PORT=6379
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=user
      - _APP_DB_PASS=password

  appwrite-worker-deletes:
    image: appwrite/appwrite:1.9.0
    entrypoint: worker-deletes
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - mariadb
      - redis
    environment:
      - _APP_ENV=development
      - _APP_OPENSSL_KEY_V1=test-secret-key-you-can-change
      - _APP_REDIS_HOST=redis
      - _APP_REDIS_PORT=6379
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=user
      - _APP_DB_PASS=password
      - _APP_STORAGE_DEVICE=Local
      - _APP_EXECUTOR_SECRET=executor-secret-key
      - _APP_EXECUTOR_HOST=http://openruntimes-executor/v1

  appwrite-worker-builds:
    image: appwrite/appwrite:1.9.0
    entrypoint: worker-builds
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - mariadb
      - redis
    environment:
      - _APP_ENV=development
      - _APP_OPENSSL_KEY_V1=test-secret-key-you-can-change
      - _APP_REDIS_HOST=redis
      - _APP_REDIS_PORT=6379
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=user
      - _APP_DB_PASS=password
      - _APP_EXECUTOR_SECRET=executor-secret-key
      - _APP_EXECUTOR_HOST=http://openruntimes-executor/v1
      - _APP_FUNCTIONS_TIMEOUT=900
      - _APP_FUNCTIONS_RUNTIMES=node-22

  appwrite-worker-functions:
    image: appwrite/appwrite:1.9.0
    entrypoint: worker-functions
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
      - openruntimes-executor
    environment:
      - _APP_ENV=development
      - _APP_OPENSSL_KEY_V1=test-secret-key-you-can-change
      - _APP_REDIS_HOST=redis
      - _APP_REDIS_PORT=6379
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=user
      - _APP_DB_PASS=password
      - _APP_EXECUTOR_SECRET=executor-secret-key
      - _APP_EXECUTOR_HOST=http://openruntimes-executor/v1
      - _APP_FUNCTIONS_TIMEOUT=900

  appwrite-worker-webhooks:
    image: appwrite/appwrite:1.9.0
    entrypoint: worker-webhooks
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
    environment:
      - _APP_ENV=development
      - _APP_OPENSSL_KEY_V1=test-secret-key-you-can-change
      - _APP_REDIS_HOST=redis
      - _APP_REDIS_PORT=6379

  openruntimes-executor:
    image: openruntimes/executor:0.7.22
    <<: *x-logging
    restart: unless-stopped
    stop_signal: SIGINT
    networks:
      - appwrite
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - openruntimes-builds:/storage/builds
      - openruntimes-functions:/storage/functions
      - /tmp:/tmp
    environment:
      - OPR_EXECUTOR_INACTIVE_TRESHOLD=600
      - OPR_EXECUTOR_MAINTENANCE_INTERVAL=600
      - OPR_EXECUTOR_NETWORK=testing_appwrite
      - OPR_EXECUTOR_SECRET=executor-secret-key
      - OPR_EXECUTOR_LOGGING_PROVIDER=
      - OPR_EXECUTOR_STORAGE_DEVICE=Local

  mariadb:
    image: mariadb:10.11
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootsecretpassword
      - MYSQL_DATABASE=appwrite
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    command: >
      mysqld
      --innodb-flush-method=fsync
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.2.4-alpine
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    command: >
      redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - appwrite-redis:/data

networks:
  appwrite:
    driver: bridge

volumes:
  appwrite-mariadb:
  appwrite-redis:
  appwrite-cache:
  appwrite-uploads:
  appwrite-certificates:
  appwrite-functions:
  appwrite-builds:
  appwrite-config:
  appwrite-sites:
  openruntimes-builds:
  openruntimes-functions:
