package dedicated

import (
	"context"
	"fmt"

	"github.com/appwrite/sdk-for-go/v7/models"
	"github.com/appwrite/terraform-provider-appwrite/internal/common"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ resource.Resource                = &branchResource{}
	_ resource.ResourceWithConfigure   = &branchResource{}
	_ resource.ResourceWithImportState = &branchResource{}
)

// branchResource manages a branch of a dedicated database: a copy that shares
// the parent's credentials but has its own host and database name, useful for
// giving a preview environment a throwaway copy of production data.
//
// A branch has no update route, so every configurable attribute forces
// replacement. When `ttl` is set the server deletes the branch on expiry; a
// refresh after that removes it from state and the next plan recreates it.
type branchResource struct {
	engine  Engine
	clients *common.AppwriteClients
}

type branchResourceModel struct {
	ID         types.String `tfsdk:"id"`
	DatabaseID types.String `tfsdk:"database_id"`
	BranchID   types.String `tfsdk:"branch_id"`
	TTL        types.Int64  `tfsdk:"ttl"`

	BranchName       types.String `tfsdk:"branch_name"`
	Namespace        types.String `tfsdk:"namespace"`
	ExpiresAt        types.Int64  `tfsdk:"expires_at"`
	Host             types.String `tfsdk:"host"`
	Port             types.Int64  `tfsdk:"port"`
	Database         types.String `tfsdk:"database"`
	Username         types.String `tfsdk:"username"`
	Password         types.String `tfsdk:"password"`
	SSL              types.Bool   `tfsdk:"ssl"`
	Engine           types.String `tfsdk:"engine"`
	ConnectionString types.String `tfsdk:"connection_string"`

	ProjectID types.String `tfsdk:"project_id"`
}

// NewBranchResource returns a constructor for the branch resource of one engine.
func NewBranchResource(engine Engine) func() resource.Resource {
	return func() resource.Resource {
		return &branchResource{engine: engine}
	}
}

func (r *branchResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = fmt.Sprintf("%s_%s_branch", req.ProviderTypeName, r.engine)
}

func (r *branchResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: fmt.Sprintf(
			"Creates a branch of a dedicated Appwrite %s database: a copy that shares the parent's credentials but has its own "+
				"host and database name.\n\n"+
				"Branches have no update route, so changing any argument replaces the branch and discards its data. A branch given "+
				"a `ttl` is deleted by the server when it expires; the next refresh then drops it from state and the following plan "+
				"recreates it.",
			r.engine.Label(),
		),
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description:   "The branch identifier, in the form `database_id/branch_id`.",
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"database_id": schema.StringAttribute{
				Description:   "The dedicated database ID to branch from.",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"branch_id": schema.StringAttribute{
				Description:   "The branch ID. Generated by the server when omitted.",
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()},
			},
			"ttl": schema.Int64Attribute{
				Description:   "How many seconds the branch lives before the server deletes it. Omit for a branch that persists until destroyed.",
				Optional:      true,
				Validators:    []validator.Int64{int64validator.AtLeast(1)},
				PlanModifiers: []planmodifier.Int64{int64planmodifier.RequiresReplace()},
			},

			"branch_name": schema.StringAttribute{Description: "The branch name.", Computed: true},
			"namespace":   schema.StringAttribute{Description: "The Kubernetes namespace the branch is deployed in.", Computed: true},
			"expires_at":  schema.Int64Attribute{Description: "The Unix timestamp when the branch expires. 0 when it does not expire.", Computed: true},
			"host":        schema.StringAttribute{Description: "The hostname to connect to the branch on.", Computed: true},
			"port":        schema.Int64Attribute{Description: "The port to connect to the branch on.", Computed: true},
			"database":    schema.StringAttribute{Description: "The database name a client sends to be routed to this branch.", Computed: true},
			"username":    schema.StringAttribute{Description: "The username to connect with. Shared with the parent database.", Computed: true},
			"ssl":         schema.BoolAttribute{Description: "Whether SSL is required for client connections.", Computed: true},
			"engine":      schema.StringAttribute{Description: "The database engine reported by the server.", Computed: true},

			"password": schema.StringAttribute{
				Description: "The password to connect with. Shared with the parent database.",
				Computed:    true,
				Sensitive:   true,
			},
			"connection_string": schema.StringAttribute{
				Description: "The full connection URI for the branch, including credentials.",
				Computed:    true,
				Sensitive:   true,
			},

			"project_id": common.ProjectIDAttribute(),
		},
	}
}

func (r *branchResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clients, ok := req.ProviderData.(*common.AppwriteClients)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *common.AppwriteClients, got: %T", req.ProviderData),
		)
		return
	}
	r.clients = clients
}

func (r *branchResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan branchResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectID, err := common.ResolveProjectID(r.clients, plan.ProjectID)
	if err != nil {
		resp.Diagnostics.AddError("Missing project_id", err.Error())
		return
	}
	api := clientFor(r.clients, r.engine, projectID)
	databaseID := plan.DatabaseID.ValueString()

	if _, err := api.CreateBranch(databaseID, CreateBranchOptions{
		BranchID: optString(plan.BranchID),
		TTL:      optInt(plan.TTL),
	}); err != nil {
		resp.Diagnostics.AddError("Error creating branch", common.FormatError(err))
		return
	}

	// CreateBranch answers with the parent database rather than the branch, and
	// there is no per-branch read route, so the branch's own connection details
	// have to come from the branch list.
	branch, err := r.findBranch(api, databaseID, plan.BranchID)
	if err != nil {
		resp.Diagnostics.AddError("Error reading created branch", err.Error())
		return
	}

	plan.ProjectID = types.StringValue(projectID)
	r.mapToState(branch, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *branchResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state branchResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectID, err := common.ResolveProjectID(r.clients, state.ProjectID)
	if err != nil {
		resp.Diagnostics.AddError("Missing project_id", err.Error())
		return
	}
	api := clientFor(r.clients, r.engine, projectID)

	list, err := api.ListBranches(state.DatabaseID.ValueString())
	if err != nil {
		// A deleted parent database takes its branches with it.
		if common.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error listing branches", common.FormatError(err))
		return
	}

	branch := findBranchByID(list, state.BranchID.ValueString())
	if branch == nil {
		// Most likely the TTL expired and the server reclaimed the branch.
		resp.State.RemoveResource(ctx)
		return
	}

	state.ProjectID = types.StringValue(projectID)
	r.mapToState(branch, &state)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update is unreachable: every configurable attribute forces replacement.
func (r *branchResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan branchResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *branchResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state branchResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectID, err := common.ResolveProjectID(r.clients, state.ProjectID)
	if err != nil {
		resp.Diagnostics.AddError("Missing project_id", err.Error())
		return
	}
	api := clientFor(r.clients, r.engine, projectID)

	if err := api.DeleteBranch(state.DatabaseID.ValueString(), state.BranchID.ValueString()); err != nil && !common.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Error deleting branch", common.FormatError(err))
	}
}

func (r *branchResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	databaseID, branchID, ok := splitImportID(req.ID)
	if !ok {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("Expected format: database_id/branch_id, got: %s", req.ID))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("database_id"), databaseID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("branch_id"), branchID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), branchID2ID(databaseID, branchID))...)
}

// findBranch locates a freshly created branch. When the ID was generated by the
// server the configuration has none to match on, so the branch is identified by
// being the only one the parent did not have before -- which the list makes
// unambiguous only when a branch ID was supplied. Without one, the newest
// branch is taken.
func (r *branchResource) findBranch(api databaseAPI, databaseID string, configuredID types.String) (*models.DedicatedDatabaseBranch, error) {
	list, err := api.ListBranches(databaseID)
	if err != nil {
		return nil, fmt.Errorf("listing branches: %s", common.FormatError(err))
	}

	if !configuredID.IsNull() && !configuredID.IsUnknown() {
		if branch := findBranchByID(list, configuredID.ValueString()); branch != nil {
			return branch, nil
		}
		return nil, fmt.Errorf("branch %q was created but is not in the branch list", configuredID.ValueString())
	}

	// A server-generated ID: the branch that expires last is the one just made,
	// since every branch shares the same TTL policy from creation time.
	var newest *models.DedicatedDatabaseBranch
	for i := range list.Branches {
		if newest == nil || list.Branches[i].ExpiresAt > newest.ExpiresAt {
			newest = &list.Branches[i]
		}
	}
	if newest == nil {
		return nil, fmt.Errorf("branch was created but the branch list is empty")
	}
	return newest, nil
}

func findBranchByID(list *models.DedicatedDatabaseBranchList, branchID string) *models.DedicatedDatabaseBranch {
	for i := range list.Branches {
		if list.Branches[i].BranchId == branchID {
			return &list.Branches[i]
		}
	}
	return nil
}

func branchID2ID(databaseID, branchID string) string {
	return databaseID + "/" + branchID
}

func (r *branchResource) mapToState(branch *models.DedicatedDatabaseBranch, model *branchResourceModel) {
	model.BranchID = types.StringValue(branch.BranchId)
	model.ID = types.StringValue(branchID2ID(model.DatabaseID.ValueString(), branch.BranchId))
	model.BranchName = types.StringValue(branch.BranchName)
	model.Namespace = types.StringValue(branch.Namespace)
	model.ExpiresAt = types.Int64Value(int64(branch.ExpiresAt))
	model.Host = types.StringValue(branch.Host)
	model.Port = types.Int64Value(int64(branch.Port))
	model.Database = types.StringValue(branch.Database)
	model.Username = types.StringValue(branch.Username)
	model.Password = types.StringValue(branch.Password)
	model.SSL = types.BoolValue(branch.Ssl)
	model.Engine = types.StringValue(branch.Engine)
	model.ConnectionString = types.StringValue(branch.ConnectionString)
}
